server:
  http_listen_port: 9080

positions:
  filename: /tmp/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: laravel
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel
          service: backend
          __path__: /var/log/app/*.log

  - job_name: nginx-access
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          service: nginx
          log_type: access
          __path__: /var/log/nginx/access.log

  - job_name: nginx-error
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          service: nginx
          log_type: error
          __path__: /var/log/nginx/error.log

    pipeline_stages:
      - regex:
          expression: '(?P<level>emerg|alert|crit|error|warn|notice|info|debug)'
      - labels:
          level:
