<?php

namespace Database\Seeders;

use App\Models\Neighborhood;
use Illuminate\Database\Seeder;

class NeighborhoodSeeder extends Seeder
{
    public function run(): void
    {
        $neighborhoods = [
            [
                'name' => 'Lekki Phase 1',
                'slug' => 'lekki-phase-1',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Eti-Osa',
                'description' => 'A well-planned residential and commercial area in the heart of Lekki, known for its upscale living, shopping malls, and excellent road network. Popular among young professionals and families.',
                'latitude' => 6.4412,
                'longitude' => 3.4718,
                'avg_rent_price' => 3500000,
                'avg_sale_price' => 85000000,
                'safety_rating' => 8,
            ],
            [
                'name' => 'Victoria Island',
                'slug' => 'victoria-island',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Eti-Osa',
                'description' => 'The commercial nerve center of Lagos, home to banks, embassies, and luxury residences. Victoria Island offers a cosmopolitan lifestyle with premium dining, nightlife, and waterfront views.',
                'latitude' => 6.4281,
                'longitude' => 3.4219,
                'avg_rent_price' => 5000000,
                'avg_sale_price' => 150000000,
                'safety_rating' => 8,
            ],
            [
                'name' => 'Ikoyi',
                'slug' => 'ikoyi',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Eti-Osa',
                'description' => 'One of the most prestigious neighborhoods in Lagos, Ikoyi is known for its tree-lined streets, luxury apartments, and proximity to the lagoon. A favorite for diplomats and high-net-worth individuals.',
                'latitude' => 6.4500,
                'longitude' => 3.4333,
                'avg_rent_price' => 6000000,
                'avg_sale_price' => 200000000,
                'safety_rating' => 9,
            ],
            [
                'name' => 'Ikeja GRA',
                'slug' => 'ikeja-gra',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Ikeja',
                'description' => 'The Government Reserved Area of Ikeja is a quiet, spacious residential neighborhood close to the airport. Known for large compounds, mature trees, and a peaceful atmosphere.',
                'latitude' => 6.5833,
                'longitude' => 3.3500,
                'avg_rent_price' => 2500000,
                'avg_sale_price' => 65000000,
                'safety_rating' => 7,
            ],
            [
                'name' => 'Yaba',
                'slug' => 'yaba',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Yaba',
                'description' => 'The tech hub of Lagos, Yaba is home to startups, co-working spaces, and the University of Lagos. A vibrant, youthful area with affordable housing options and a thriving street food scene.',
                'latitude' => 6.5097,
                'longitude' => 3.3792,
                'avg_rent_price' => 1200000,
                'avg_sale_price' => 35000000,
                'safety_rating' => 6,
            ],
            [
                'name' => 'Surulere',
                'slug' => 'surulere',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Surulere',
                'description' => 'A bustling residential area with a rich cultural heritage. Surulere is famous for the National Stadium, National Theatre, and a mix of old and new Lagos. Great for families on a budget.',
                'latitude' => 6.4969,
                'longitude' => 3.3564,
                'avg_rent_price' => 900000,
                'avg_sale_price' => 25000000,
                'safety_rating' => 6,
            ],
            [
                'name' => 'Ajah',
                'slug' => 'ajah',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Eti-Osa',
                'description' => 'A rapidly developing area at the end of the Lekki-Epe Expressway. Ajah offers more affordable alternatives to Lekki and VI with new estates, shopping centers, and improving infrastructure.',
                'latitude' => 6.4667,
                'longitude' => 3.5833,
                'avg_rent_price' => 1500000,
                'avg_sale_price' => 40000000,
                'safety_rating' => 6,
            ],
            [
                'name' => 'Banana Island',
                'slug' => 'banana-island',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Eti-Osa',
                'description' => 'An exclusive, man-made island off Ikoyi that is home to the wealthiest Nigerians. Features ultra-luxury villas, 24/7 security, and waterfront living. The most expensive real estate in West Africa.',
                'latitude' => 6.4560,
                'longitude' => 3.4270,
                'avg_rent_price' => 15000000,
                'avg_sale_price' => 800000000,
                'safety_rating' => 10,
            ],
            [
                'name' => 'Gbagada',
                'slug' => 'gbagada',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Kosofe',
                'description' => 'A middle-class residential area on the mainland with good access to the Island via Third Mainland Bridge. Gbagada offers decent housing, schools, and healthcare facilities.',
                'latitude' => 6.5525,
                'longitude' => 3.3889,
                'avg_rent_price' => 1000000,
                'avg_sale_price' => 30000000,
                'safety_rating' => 6,
            ],
            [
                'name' => 'Magodo',
                'slug' => 'magodo',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Kosofe',
                'description' => 'An upscale residential estate on the mainland with well-organized streets and gated communities. Magodo is popular among families seeking space and serenity away from the Island hustle.',
                'latitude' => 6.6150,
                'longitude' => 3.3800,
                'avg_rent_price' => 2000000,
                'avg_sale_price' => 55000000,
                'safety_rating' => 7,
            ],
            [
                'name' => 'Lekki Phase 2',
                'slug' => 'lekki-phase-2',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Eti-Osa',
                'description' => 'The extension of Lekki with newer developments, more affordable prices, and growing commercial activity. Features several new estates and is quickly becoming a hotspot for investment.',
                'latitude' => 6.4500,
                'longitude' => 3.5167,
                'avg_rent_price' => 2000000,
                'avg_sale_price' => 50000000,
                'safety_rating' => 7,
            ],
            [
                'name' => 'Maryland',
                'slug' => 'maryland',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'lga' => 'Ikeja',
                'description' => 'A central Lagos location connecting the mainland to Ikorodu Road. Maryland is known for its shopping mall, medical facilities, and easy access to both sides of Lagos.',
                'latitude' => 6.5700,
                'longitude' => 3.3650,
                'avg_rent_price' => 1200000,
                'avg_sale_price' => 35000000,
                'safety_rating' => 6,
            ],
        ];

        foreach ($neighborhoods as $neighborhood) {
            Neighborhood::create($neighborhood);
        }
    }
}
